In [1]:
import pandas as pd 
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm

from matplotlib import colors
from matplotlib.ticker import PercentFormatter
# regression analysis


import sys
import os
from pathlib import Path

module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path+"\\utils")

from players_season_builder import *

In [2]:
player_path = r"\Users\sebas\Desktop\UChicago - Q6\Sports Analytics\sports_analytics_project\data\BDB_Player.xlsx"

df_player = pd.read_excel(player_path)

In [3]:
df_player.columns = ['DATASET', 'DATE', 'PLAYER FULL NAME', 'POSITION', 'OWN TEAM',
       'OPP TEAM', 'VENUE', 'MIN', 'FG', 'FGA', '3P', '3PA', 'FT', 'FTA', 'OR',
       'DR', 'TOT', 'A', 'PF', 'ST', 'TO', 'BL', 'PTS', 'PER', 'DATE-DIFF',
       'RR VAL', 'RR SERIES', 'S_PER', 'I_PER', 'SAME CITY', 'TRAVEL',
       '1.0 days', '10.0 days', '11.0 days', '12.0 days', '13.0 days',
       '14+ days', '14.0 days', '2.0 days', '3.0 days', '4.0 days', '5.0 days',
       '6.0 days', '7.0 days', '8.0 days', '9.0 days', 'Season Start days',
       'H', 'R', 'H-M1', 'H-M2', 'H-M3', 'R-M1', 'R-M2', 'R-M3', 'M1', 'M2',
       'M3', 'S_OEFF', 'S_DEFF', 'I_OEFF', 'I_DEFF']

In [27]:
df_player = df_player[df_player['I_PER'].notnull()]
y = df_player[['PER']]
x = df_player.loc[:, ~df_player.columns.isin(['DATASET', 'DATE', 'PLAYER FULL NAME', 'POSITION', 'OWN TEAM',
       'OPP TEAM', 'VENUE', 'MIN','DATE-DIFF', 'RR VAL', 'RR SERIES','PER']) ]

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

In [28]:
reg = LinearRegression()  
reg.fit(X_train, y_train)

LinearRegression()

In [26]:
reg.intercept_

array([0.14496433])

In [29]:
attributes_coefficients = pd.DataFrame(
    reg.coef_[0], 
    x.columns, columns=['Coefficient'])  
attributes_coefficients

                    Coefficient
FG                -1.283661e+09
FGA               -7.758004e-01
3P                -6.418303e+08
3PA               -2.742912e-02
FT                -6.418303e+08
FTA               -3.948714e-01
OR                -4.218720e+09
DR                -4.218720e+09
TOT                4.218720e+09
A                 -1.399653e-03
PF                 4.521454e-03
ST                 1.052583e+00
TO                -1.048603e+00
BL                 7.767568e-01
PTS                6.418303e+08
S_PER              7.772930e-03
I_PER             -1.045066e-02
SAME CITY         -2.095116e-02
TRAVEL            -4.196121e-04
1.0 days           1.760428e+09
10.0 days          1.760428e+09
11.0 days          1.760428e+09
12.0 days          1.760428e+09
13.0 days          1.760428e+09
14+ days           1.760428e+09
14.0 days          1.760428e+09
2.0 days           1.760428e+09
3.0 days           1.760428e+09
4.0 days           1.760428e+09
5.0 days           1.760428e+09
6.0 days           1.760428e+09
7.0 days           1.760428e+09
8.0 days           1.760428e+09
9.0 days           1.760428e+09
Season Start days  1.760428e+09
H                  1.451935e+09
R                  1.451935e+09
H-M1               8.958180e+08
H-M2               1.419997e+09
H-M3               5.011216e+09
R-M1               8.958180e+08
R-M2               1.419997e+09
R-M3               5.011216e+09
M1                -8.958180e+08
M2                -1.419997e+09
M3                -5.011216e+09
S_OEFF            -3.651097e-02
S_DEFF             4.904004e-03
I_OEFF             2.087947e-02
I_DEFF            -2.179162e-02

In [68]:
y_pred = reg.predict(X_test)
print( y_test.values.shape )
print( y_pred.shape )
print( type(y_test.values) )
print( type(y_pred))
print(y_test.values[:5])
print(y_pred[:5])

(43323, 1)
(43323, 1)
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[[ 6.5635212 ]
 [ 0.84836585]
 [ 2.43143348]
 [12.00156131]
 [ 8.8437306 ]]
[[ 6.62533712]
 [ 0.90249538]
 [ 2.49666977]
 [11.91835403]
 [ 8.90100288]]

In [80]:
comparison = pd.DataFrame(
        {
        'Actual': list(y_test.values), 
        'Predicted': list(y_pred)
        }
    )  
comparison

                     Actual             Predicted
0       [6.563521198957533]    [6.62533712387085]
1      [0.8483658466156834]  [0.9024953842163086]
2       [2.431433479879607]  [2.4966697692871094]
3       [12.00156130970056]  [11.918354034423828]
4       [8.843730596163631]   [8.901002883911133]
...                     ...                   ...
43318   [8.436077326216854]   [8.214860916137695]
43319   [6.766950713889353]   [6.590062141418457]
43320   [14.09235604454073]  [14.230885028839111]
43321   [20.66179975227115]  [20.698705196380615]
43322  [0.6417355695748751]  [1.0834884643554688]

[43323 rows x 2 columns]

In [31]:
from sklearn import metrics  
print('MAE:', metrics.mean_absolute_error(y_test, y_pred))  
print('MSE:', metrics.mean_squared_error(y_test, y_pred))  
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

MAE: 0.14935101592197256
MSE: 0.03915612368724233
RMSE: 0.1978790632867518